"""Repository protocol shared by the service layer."""

from __future__ import annotations

from typing import Any, Protocol


class RepositoryStore(Protocol):
    def ensure_user_workspace(self, username: str) -> dict[str, Any]: ...

    def list_projects(self, username: str | None = None) -> list[dict[str, Any]]: ...

    def create_project(self, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def publish_project(self, project_id: str, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def copy_shared_project(self, project_id: str, username: str, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...

    def get_project(self, project_id: str) -> dict[str, Any]: ...

    def list_branches(self, project_id: str) -> list[dict[str, Any]]: ...

    def create_branch(self, project_id: str, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def merge_branch(
        self,
        project_id: str,
        target_branch: str,
        source_branch: str,
        username: str,
        force: bool,
    ) -> dict[str, Any]: ...

    def list_elements(
        self,
        project_id: str,
        branch_name: str,
        element_type: str | None = None,
        query: str | None = None,
    ) -> list[dict[str, Any]]: ...

    def upsert_element(self, project_id: str, branch_name: str, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def get_element(self, project_id: str, branch_name: str, element_id: str) -> dict[str, Any]: ...

    def delete_element(self, project_id: str, branch_name: str, element_id: str, username: str) -> dict[str, Any]: ...

    def commit(self, project_id: str, branch_name: str, message: str, username: str) -> dict[str, Any]: ...

    def list_commits(self, project_id: str) -> list[dict[str, Any]]: ...

    def diff_commits(
        self,
        project_id: str,
        branch_name: str,
        from_ref: str | None,
        to_ref: str | None,
    ) -> dict[str, Any]: ...

    def rollback(self, project_id: str, branch_name: str, commit_id: str, username: str) -> dict[str, Any]: ...

    def list_tags(self, project_id: str) -> list[dict[str, Any]]: ...

    def create_tag(self, project_id: str, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def list_audit(self, project_id: str, limit: int = 80) -> list[dict[str, Any]]: ...

    def import_elements(self, project_id: str, branch_name: str, payload: dict[str, Any], username: str) -> dict[str, Any]: ...

    def export_branch_xmi(self, project_id: str, branch_name: str) -> str: ...

    def export_branch(self, project_id: str, branch_name: str) -> dict[str, Any]: ...

    def validate_branch(self, project_id: str, branch_name: str) -> dict[str, Any]: ...

    def get_branch(self, project_id: str, branch_name: str) -> dict[str, Any]: ...

    def list_documents(self, project_id: str, branch_name: str) -> list[dict[str, Any]]: ...

    def get_document(self, project_id: str, branch_name: str, document_id: str) -> dict[str, Any]: ...

    def touch_project(self, project_id: str) -> None: ...

    def save(self) -> None: ...

    def record_audit(
        self,
        project_id: str,
        branch_name: str,
        action: str,
        actor: str,
        element_id: str | None = None,
        detail: dict[str, Any] | None = None,
    ) -> None: ...
